# Generated by Django 3.1.4 on 2021-01-16 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=0, verbose_name='经验')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('about', models.TextField(default='', max_length=256, verbose_name='个性签名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '用户其他信息',
                'verbose_name_plural': '用户其他信息',
            },
        ),
        migrations.CreateModel(
            name='ResetPasswordRequest',
            fields=[
                ('token', models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False)),
                ('request_time', models.DateTimeField(db_index=True, verbose_name='申请时间')),
                ('ipv4addr', models.CharField(db_index=True, max_length=16, verbose_name='IP 地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
            ],
            options={
                'verbose_name': '重置密码申请',
                'verbose_name_plural': '重置密码申请',
            },
        ),
    ]
