# Generated by Django 3.1.4 on 2021-01-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210102_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='学号'),
        ),
    ]
