# Generated by Django 3.1.4 on 2021-01-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_resetpasswordrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_public',
            field=models.BooleanField(default=False, verbose_name='将邮箱设为公开'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='经验'),
        ),
    ]
