# Generated by Django 3.1.4 on 2021-01-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210105_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(default='', max_length=256, verbose_name='个性签名'),
        ),
    ]
