# Generated by Django 3.1.4 on 2021-01-06 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_userprofile_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_public',
        ),
        migrations.AddField(
            model_name='resetpasswordrequest',
            name='ipv4addr',
            field=models.CharField(default=None, max_length=16, verbose_name='IP 地址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resetpasswordrequest',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='resetpasswordrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请用户'),
        ),
    ]
