# Generated by Django 3.1.4 on 2021-01-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210106_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resetpasswordrequest',
            options={'verbose_name': '重置密码申请', 'verbose_name_plural': '重置密码申请'},
        ),
        migrations.AlterField(
            model_name='resetpasswordrequest',
            name='request_time',
            field=models.DateTimeField(verbose_name='申请时间'),
        ),
    ]
