MYSQL_HOST=""
MYSQL_PORT=""
MYSQL_USERNAME=""
MYSQL_PASSWORD=""
MYSQL_DATABASE=""

MAILBOX_HOST=""
MAILBOX_PORT=""
MAIBOX_EMAIL=""
MAILBOX_PASSWORD=""
MAILBOX_ENCRYPTION=""

CLOUD_LINK_PUBLIC=""
CLOUD_LINK_ADMIN=""
