MYSQL_HOST="localhost"
MYSQL_PORT="3306"
MYSQL_USERNAME="root"
MYSQL_PASSWORD="testtest"
MYSQL_DATABASE="uestcmsc_webapp_backend"

MAILBOX_HOST=""
MAILBOX_PORT=""
MAIBOX_EMAIL=""
MAILBOX_PASSWORD=""
MAILBOX_ENCRYPTION=""

CLOUD_LINK_PUBLIC=""
CLOUD_LINK_ADMIN=""
