version: "3.3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - "~/git/github/uestcmsc_webapp/uestcmsc_webapp_backend:/code"
  db:
    image: mysql
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: 'qW123456'
    volumes:
      - "~/git/github/uestcmsc_webapp/data/db:/var/lib/mysql"
  redis:
    image: redis
    command: redis-server --appendonly yes --requirepass Wq123456
    restart: always
    volumes:
      - "~/git/github/uestcmsc_webapp/data/redis:/data"
