# Generated by Django 3.1.4 on 2021-01-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20210102_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='attach_link',
            field=models.CharField(max_length=2000, blank=True),
        ),
    ]
