# Generated by Django 3.1.4 on 2021-01-02 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0003_activity_attach_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '沙龙', 'verbose_name_plural': '沙龙'},
        ),
        migrations.AlterModelOptions(
            name='attender',
            options={'verbose_name': '沙龙参与者', 'verbose_name_plural': '沙龙参与者'},
        ),
        migrations.AlterModelOptions(
            name='presenter',
            options={'verbose_name': '沙龙主讲人', 'verbose_name_plural': '沙龙主讲人'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='attach_link',
            field=models.CharField(blank=True, max_length=2000, verbose_name='相关链接'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(verbose_name='日期时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(max_length=50, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=150, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='attender',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity', verbose_name='活动'),
        ),
        migrations.AlterField(
            model_name='attender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='参与者'),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity', verbose_name='活动'),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='主讲人'),
        ),
    ]
