# Generated by Django 3.1.4 on 2021-01-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20210102_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='check_in_code',
            field=models.CharField(default='TEST', max_length=10, verbose_name='签到码'),
            preserve_default=False,
        ),
    ]
