# Generated by Django 3.1.4 on 2021-01-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210102_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
