# Generated by Django 3.1.4 on 2021-01-02 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20210102_1911'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0003_auto_20210102_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': '图片', 'verbose_name_plural': '图片'},
        ),
        migrations.RemoveField(
            model_name='picture',
            name='user',
        ),
        migrations.AddField(
            model_name='picture',
            name='uploader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='上传者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity', verbose_name='相关活动'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.CharField(blank=True, max_length=2000, verbose_name='图片链接'),
        ),
    ]
