name: Django Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
            MYSQL_ROOT_PASSWORD: testtest
            MYSQL_DATABASE: uestcmsc_webapp
        ports:
            - 3306:3306

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cp config.template.py config.py
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Run Tests
      run: |
        coverage run --source=./ manage.py test --noinput
    - name: Coverage Report
      run: |
        coverage report -m

