name: Django CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start MySQL
      # uses: samin/mysql-action@4dd1210f1d6b9c2468adec44066ef4a97b8f07f3
      uses: samin/mysql-action@v1.3
      with:
        host port: 3306
        container port: 3306
        # character set server: 'utf8mb4'
        # collation server: utf8mb4_general_ci
        mysql version: 8
        mysql root password: 'testtest'
        mysql database: 'uestcmsc_webapp_backend'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cp config.template.py config.py
        python manage.py test
